# Data vis with Tableau

## Introduction

Tableau Public is a free platform to publicly share and explore data visualizations online. Anyone can create visualizations using either Tableau Desktop Professional Edition or the free Tableau Public Edition. 

For this course we're using Tableau Public in browser, which is free. Create account at: public.tableau.com. To follow the first examples use this [link](https://public.tableau.com/profile/grow.with.google#!/)

To work with data, click on the World Happiness data and click the button in the top right to make a copy. At this point, Tableau will save a copy of this workbook to your own profile so you can create your own visualizations. Now that you're working in your own copy, create a new worksheet so you can build a data viz from scratch. You'll click on Worksheet in the top menu and then New Worksheet. To start building your data viz, add country as a detail in the marks shelf. You can do this by dragging the country table over to the detail icon. This sets up your viz as a world map to represent the data in the table.

Next, add the happiness score to the color on the mark shelf. This applies a color scheme to the viz, in this case shades of blue. So, to adjust the colors, click the color menu and click edit colors. Then change the color scheme to green, blue, diverging and check the box for stepped colors, which shows a clear difference between the highest and lowest happiness score.

Because there are three years of data in the table we're using, you can filter the data to only include 2016. So, we'll add year to the filter shelf. Then we'll choose to filter by year and we'll select 2016.

We can also focus our visualization on one region, the European region. To do this, move your cursor to the left part of the map to find the view toolbar. Use the tools in this toolbar to pan to and zoom in on the European region.

Use the lasso selection tool to select just a few countries. Keep only, this applies another filter this time to the country you're including in your viz. 

To make your viz even better, add the happiness score as a label in the map. You can now see a happiness score for each country on the map. There's an option to change the data type of the happiness scores from decimals to whole numbers. But when you do this, you lose the contrast that the values with the decimals offers. So, change it back to show the happiness score as a decimal.

Now, to make it even more interactive, let's add a filter with a slider. This will allow your audience to filter by happiness score so they can focus on fewer countries. 

But first, let's bring in more of the map we started with. To do this, hover on the map and select the zoom home icon in the toolbar to reveal more countries on the map. 

Next, we're going to add happiness score to the filter shelf. We'll select all values and click next. Then, for the range of values we'll click OK to accept the default settings. In the filters shelf, click the drop down to open the menu for the happiness score and select Show Filter.


Resources:

- [Google Career Certificates page on Tableau Public](https://public.tableau.com/profile/grow.with.google#!/): This gallery contains all of the visualizations created in the video lessons; you can explore these examples more here. 
- [Tableau Public resources page](https://public.tableau.com/en-us/s/resources): This links to the resources page, including some how-to videos and sample data.
- [Tableau user forum](https://community.tableau.com/s/): Search for answers and connect with other users in the community on the forum page. 
- [Which chart or graph is right for you?](http://www.tableau.com/sites/default/files/media/which_chart_v6_final_0.pdf) This presentation covers 13 of the most popular charts in Tableau.
- [The Ultimate Cheat Sheet on Tableau Charts.](https://towardsdatascience.com/the-ultimate-cheat-sheet-on-tableau-charts-642bca94dde5) This blog describes 24 chart variations in Tableau and guidelines for use. 


## Creating a data vis

For this tutorial, we use the data in `../data/CO2-Dataset.xlsx` to make a database that demonstrates the amount of CO2 emissions that come from each country

- Log into tableau public, go to my profile and create a vis
- From the connect to data window, go to the files tab and upload the CO2 dataset
- After the data uploads, the screen will show the data source interface. Underneath connections, double click on the sheet's CO2 data cleaned to load that data into the main part of the screen. You can also drag and drop the sheet into the area where it says drag tables here
- Underneath connections, double click on the sheet's CO2 data cleaned to load that data into the main part of the screen.
- Click update now to preview the data you opened in the bottom portion of the screen. By default, Tableau will only show the first 1000 rows in the table, but you can increase the number of rows in the setting above the data view. Each row corresponds to a single data point and each column represents a different feature. Tableau interprets the type of data in each column. Each icon represents a different type of data. For example, a number sign represents numerical data while an abc represents string data. A globe represents geographic data and so on. 
- To start the database, choose the sheet 1 tab in the lower left of the display.On the far left of the screen is a banner with column names above a grey line. In tableau, these are called the **dimensions** of the data. Below this line are the different **measures** that you can track for these dimensions. 
- To create a chart that displays the CO2 emissions per country, we're going to start by double clicking the country name dimension.The main display will show a map of the countries on the planet with dots indicating which countries are represented in the data.
- Double click or drag and drop onto the sheet the measures CO2 kilotons. This will change the size of the dots to be proportional to the amount of CO2 emitted.Tableau has a wide selection of options for depicting the measures for a given dimension. Most of these options are contained in the middle column between the main display and the columns with dimensions and measures
- Now, let's customize the look of our chart to better communicate trends in the data. If we drag and drop a measure on one of the marks such as color, size and label, we can change that aspect of the measures visualization on the chart. For instance, say we want to change the color of the CO2 measure. We would drag the measure CO2 kilotons to the box with the color label.
- But what if we wanted to change the dimensions or measures? Instead of visualizing the CO2 per country, maybe we want to chart the CO2 per capita per region. To do this, we could double click on the dimension region and then do the same for the measure CO2 per capita. This builds a new chart.


## Data vis in tableau

- A **diverging color** palette displays two ranges of values using color intensity to show the magnitude of the number and the actual color to show which range the numbers from.

A diverging color palette in Tableau displays a value’s range by color hue and a value’s magnitude by color intensity. The color palette isn’t used to indicate a margin of error for displayed values.


## Getting creative

For this exercise, lets go to the happiness data againt to use this data in this table to figure out what the biggest contributors to a country's happiness score are

1. Worksheet --> new worksheet
2. Set the year filter to 2016
3. Add Happiness score to the rows shelf and economy to the column shelf, drag country to the details section creating a separate circle for each country and a scatterplot for our data
4. Click the analytics tab
5. Add a trend line
6. Duplicate the sheet to keep original formatting
7. Replace economy with family
8. Rename sheets to economy and family, do the same for health and generosity
9. New Dashbord, drag and drop tables into this




## Working with multiple data sources

Scenario: You need to create a visualization that shows the CO2 emissions per capita for each country from 2000-2011. You'll also provide information about each country's population GDP and energy use.

1. Upload CO2 dataset
1. Go to data source tab and the connections column, in there use the plus icon to add the energy table, gdp and then population
1. Link these tables with joins: First remove the energy by dragging it back into the connections tab
1. In CO2 data, click and drag the cleaned data to multiple connections and double click box to open the physical table and create joins
1. Open energy and drag energy sheet to right side to CO2 data box. Select year on the left and right to decide what to join on, select country name and country as join clause, close the menu by clicking X
1. Year and Year1 have a number sign above it, sth we need to change: click on them and select data. After changing Year (CO2 Data Cleaned) to a Date type, the data preview pane will no longer display properly. To fix this, go to the column list in the lower left of the screen. Select the # icon next to the Year1 (Energy) column. Then, change the data type to Date.
1. Drag gdp table under the energy box, change year to date, add new join clause with country name and country1
1. Add Pop, change year to date,  add new join clause with country name and country total pop
1. Change energy use type to number decimal
1. Change current gdp to number whole
1. Go to sheet1
1. Drag country name to details, CO2 per capita to color
1. Choose the square and edit colors and change to red green diverging and select stepped color and reverse; in show advanced add 0 and 
1. Drag year into the filters area, years, next, all, ok
1. In filters, right click on year, select show filter, in the new box, seelct year of year and single value, dropdown
1. 
