# Data, data everywhere

## Introduction to data science

Here, we find notes covered in Weeks 1 and 2.

### Useful terms

- Data: A collection of facts
- Data analysis: the collection, transformation, and organization of data in order to draw conclusions, make predictions, and drive informed decision-making
- Data science  is an umbrella term that encompasses three disciplines: 
    - Machine learning
    - Statistics
    - Analytics

- People analytics is the practice of collecting and analyzing data on the people who make up a company’s workforce in order to gain insights to improve how the company operates
- Business analytics is "the use of math and statistics to derive meaning from data in order to make better business decisions"
- [Examples of buisness analytics in action](https://online.hbs.edu/blog/post/business-analytics-examples)

- Steps in the analysis process:
    - Ask questions and define the problem
    - Prepare data by collecting and storing the information
    - Process data by cleaning and checking the information
    - Analyze data to find patterns, relationships, and trends
    - Share data with your audience
    - Act on the data and use the analysis results


### The data ecosystem

- Ecosystem: a group of elements that interact with one another
- Data ecosystems: the various elements that interact with one another in order to produce, manage, store, organize, analyze, and share data. These elements include hardware and software tools and the people that use them
- The cloud: a place to keep data online, rather than on a computer hard drive
- Data science:  creating new ways of modeling and understanding the unknown by using raw data
- **Data scientists** create new questions using data, while **analysts** find answers to existing questions by creating insights from data sources



### Data and decision making

- Data-driven decision-making is defined as using facts to guide business strategy
- Important questions to ask:
    - What kind of results are needed?
    - Who will be informed?
    - Am I answering the question being asked?
    - How quickly does a decision need to be made?



## Data analyst skills

### Basic terms

- Analytical skills: Qualities and characteristics associated with solving problems using facts
- Important skills include:
    - **Curiosity**
    - **Understanding context**, i.e. understanding the condition in which something exists or happens
    - Having a **technical mindset**, i.e. the ability to break things down into smaller steps or pieces and work with them in an orderly way
    - **Data design**, i.e. how we organize information
    - **Data strategy**, i.e. the management of the people, processes and tools used in data analysis



### Analytical thinking

- Definition: Identifying and defining a problem and then solving it by using data in an organized, step-by-step manner
- Key aspects:
    - **Visualization**: the graphical representation of information; important to understand and explain information
    - **Strategy**: Helps data analysts see what they want to achieve with the data and how they can get there. Strategy also helps improve the quality and usefulness of the data we collect
    - **Problem-orientation**: Data analysts use a problem- oriented approach in order to identify, describe, and solve problems
    - **Correlation**: being able to identify a correlation between two or more pieces of data
    - **Big-picture and detail-oriented thinking**: being able to see the big picture as well as the details

Let's talk about some of the questions data analysts ask when they're on the hunt for a solution. 

Here's one that will come up a lot: 

- What is the root cause of a problem? A **root cause** is the reason why a problem occurs. 
A simple way to wrap your head around root causes is with the process called the **Five Whys**. In the Five Whys you ask "why" five times to reveal the root cause.
- Where are the gaps in our process? For this, many people will use something called gap analysis. **Gap analysis** lets you examine and evaluate how a process works currently in order to get where you want to be in the future. The general approach to gap analysis is understanding where you are now compared to where you want to be. Then you can identify the gaps that exist between the current and future state and determine how to bridge them
- What did we not consider before? 




## Following the data life cycle

### Phases in the life cycle of data

**Database**: A collection of data stored in a computer system

Individual stages in the data life cycle will vary from company to company or by industry or sector but in general key steps are:

1. **Plan**: During planning, a business decides what kind of data it needs, how it will be managed throughout its life cycle, who will be responsible for it, and the optimal outcomes
2. **Capture**: This is where data is collected from a variety of different sources, i.e. from outside resources or company documents, and brought into the organization
3. **Manage**: How we care for our data, how and where it's stored, the tools used to keep it safe and secure, and the actions taken to make sure that it's maintained properly
4. **Analyze**:  the data is used to solve problems, make great decisions, and support business goals
5. **Archive**: storing data in a place where it's still available, but may not be used again
6. **Destroy**: destroy data via a secure data erasure software, this is important to protect private information

Be careful not to mix up or confuse the six stages of the data life cycle (Plan, Capture, Manage, Analyze, Archive, and Destroy) with the six phases of the data analysis life cycle (Ask, Prepare, Process, Analyze, Share, and Act). They shouldn't be used or referred to interchangeably.



### The data analysis process

Now that you understand all the phases of the data life cycle, it's time to move on to the phases of data analysis. They sound similar, but are two different things. Data analysis isn't a life cycle. It's the process of analyzing data.


#### Ask step

We define the problem to be solved and we make sure that we fully understand stakeholder expectations.

**Stakeholders** are people who have invested time and resources into a project and are interested in the outcome

Defining a problem means you look at the current state and identify how it's different from the ideal state.

Another important part of the ask phase is understanding stakeholder expectations. The first step here is to determine who the stakeholders are. That may include your manager, an executive sponsor, or your sales partners.


#### Prepare step

Here, the data analysts collect and store data they'll use for the upcoming analysis process. Decisions made from your analysis should always be based on facts and be fair and impartial.


#### Process step

Here, data analysts find and eliminate any errors and inaccuracies that can get in the way of results. This usually means cleaning data, transforming it into a more useful format, combining two or more data sets to make information more complete and removing outliers, which are any data points that could skew the information. You'll also fix typos, inconsistencies, or missing and inaccurate data


#### Analysis step

Analyzing the data you've collected involves using tools to transform and organize that information so that you can draw useful conclusions, make predictions, and drive informed decision-making


#### Share step

Here you'll learn how data analysts interpret results and share them with others to help stakeholders make effective data-driven decisions. In the share phase, visualization is a data analyst's best friend. 


#### Act step

This is the exciting moment when the business takes all of the insights you, the data analyst, have provided and puts them to work in order to solve the original business problem



### Data analysis tools

The most commonly used tools are: 

- **Spreadsheets**: 
    - Spreadsheets structure data in a meaningful way by letting you Collect, store, organize, and sort information AND identify patterns and piece the data together in a way that works for each specific data project AND create excellent data visualizations, like graphs and charts. 
    - For example excel or google sheets.
    - Uses formulas, a set of instructions that performs a specific calculation using the data in a spreadsheet
    - Uses functions, i.e. preset command that automatically performs a specific process or task using the data in a spreadsheet
    
- **Query languages**: 
    - A query language is a computer programming language that allows you to retrieve and manipulate data from a database
    - A database is a collection of data stored in a computer system
    - Sequel, i.e. structured query language, SQL is a language that lets data analysts communicate with a database
    - These languages allow us to isolate specific information from a database(s),  learn and understand the requests made to databases and finally allows us to select, create, add, or download data from a database for analysis

- **Visualization tools**: 
    - I.e. the graphical representation of information, includes graphs, maps or tables
    - Example tools: Tableau, Looker

Differences between spreadsheets and databases:

Spreadsheets |	Databases
- | -
Software applications | Data stores - accessed using a query language (e.g. SQL)
Structure data in a row and column format | Structure data using rules and relationships
Organize information in cells | Organize information in complex collections
Provide access to a limited amount of data | Provide access to huge amounts of data
Manual data entry | Strict and consistent data entry
Generally one user at a time | Multiple users
Controlled by the user | Controlled by a database management system








