# Effective questions

**Structured thinking** is the process of recognizing the current problem or situation, organizing available information, revealing gaps and opportunities, and identifying the options


## The six data analysis phases

### Ask

It’s impossible to solve a problem if you don’t know what it is. These are some things to consider:

- Define the problem you’re trying to solve 
- Make sure you fully understand the stakeholder’s expectations
- Focus on the actual problem and avoid any distractions
- Collaborate with stakeholders and keep an open line of communication
- Take a step back and see the whole situation in context

Questions to ask yourself in this step: 

- What are my stakeholders saying their problems are?
- Now that I’ve identified the issues, how can I help the stakeholders resolve their questions?


### Prepare

You will decide what data you need to collect in order to answer your questions and how to organize it so that it is useful. You might use your business task to decide: 

- What metrics to measure
- Locate data in your database
- Create security measures to protect that data

Questions to ask yourself in this step: 

- What do I need to figure out how to solve this problem?
- What research do I need to do?


### Process

Clean data is the best data and you will need to clean up your data to get rid of any possible errors, inaccuracies, or inconsistencies. This might mean:

- Using spreadsheet functions to find incorrectly entered data 
- Using SQL functions to check for extra spaces
- Removing repeated entries
- Checking as much as possible for bias in the data

Questions to ask yourself in this step: 

- What data errors or inaccuracies might get in my way of getting the best possible answer to the problem I am trying to solve?
- How can I clean my data so the information I have is more consistent?


### Analyse

You will want to think analytically about your data. At this stage, you might sort and format your data to make it easier to: 

- Perform calculations
- Combine data from multiple sources
- Create tables with your results

Questions to ask yourself in this step:

- What story is my data telling me?
- How will my data help me solve this problem?
- Who needs my company’s product or service? What type of person is most likely to use it?


### Share

Everyone shares their results differently so be sure to summarize your results with clear and enticing visuals of your analysis using data via tools like graphs or dashboards. This is your chance to show the stakeholders you have solved their problem and how you got there. Sharing will certainly help your team:  

- Make better decisions
- Make more informed decisions
- Lead to stronger outcomes
- Successfully communicate your findings

Questions to ask yourself in this step:

- How can I make what I present to the stakeholders engaging and easy to understand?
- What would help me understand this if I were the listener?


### Act

Now it’s time to act on your data. You will take everything you have learned from your data analysis and put it to use. This could mean providing your stakeholders with recommendations based on your findings so they can make data-driven decisions.

Questions to ask yourself in this step:

- How can I use the feedback I received during the share phase (step 5) to actually meet the stakeholder’s needs and expectations?


These six steps can help you to break the data analysis process into smaller, manageable parts, which is called **structured thinking**. This process involves four basic activities:

- Recognizing the current problem or situation
- Organizing available information 
- Revealing gaps and opportunities
- Identifying your options



## Common problem types

1. **Making predictions**: using data to make an informed decision about how things may be in the future
2. **Categorizing things**: assigning information to different groups or clusters based on common features
3. **Spotting something unusual**: identify data that is different from the norm
4. **Identifying themes**:  Identifying themes takes categorization as a step further by grouping information into broader concepts
5. **Discovering connections**:  enables data analysts to find similar challenges faced by different entities, and then combine data and insights to address them
6. **Finding patterns**: Data analysts use data to find patterns by using historical data to understand what happened in the past and is therefore likely to happen again



## SMART questions

Here's an example that breaks down the thought process of turning a problem question into one or more SMART questions using the SMART method: What features do people look for when buying a new car?

- **Specific**: Specific questions are simple, significant and focused on a single topic or a few closely related ideas. I.e. what percentage of kids achieve the recommended 60 minutes of physical activity at least five days a week instead of asking are kids getting enough physical activities these days??
- **Measurable**: Measurable questions can be quantified and assessed. An example of an unmeasurable question would be, why did a recent video go viral? Instead, you could ask how many times was our video shared on social channels the first week it was posted?
- **Action-oriented**: Action-oriented questions encourage change. Rather than asking, how can we get customers to recycle our product packaging? You could ask, what design features will make our packaging easier to recycle?
- **Relevant**: Relevant questions matter, are important and have significance to the problem you're trying to solve. Let's say you're working on a problem related to a threatened species of frog. And you asked, why does it matter that Pine Barrens tree frogs started disappearing? This is an irrelevant question because the answer won't help us find a way to prevent these frogs from going extinct. A more relevant question would be, what environmental factors changed in Durham, North Carolina between 1983 and 2004 that could cause Pine Barrens tree frogs to disappear from the Sandhills Regions?
- **Time-bound**: Time-bound questions specify the time to be studied. 

Questions should be open-ended. This is the best way to get responses that will help you accurately qualify or disqualify potential solutions to your specific problem.

### Things to avoid: 

Below some examples of ineffective questions

- **Leading questions**: questions that only have a particular response, such as this product is too expensive, isn’t it? A better question might be, 'What is your opinion of this product?'
- **Closed-ended questions**: questions that ask for a one-word or brief response only, such as were you satisfied with the customer trial? This is a closed-ended question because it doesn’t encourage people to expand on their answer. It is really easy for them to give one-word responses that aren’t very informative. A better question might be, 'What did you learn about customer experience from the trial.'
- **Vague questions**: questions that aren’t specific or don’t provide context, i.e. does the tool work for you? This question is too vague because there is no context. Is it about comparing the new tool to the one it replaces? You just don’t know. A better inquiry might be, 'When it comes to data entry, is the new tool faster, slower, or about the same as the old tool? If faster, how much time is saved? If slower, how much time is lost?'



## Understanding the power of data

Keep in mind, it is possible to have solid data and still make the wrong choices. It is up to data analysts to interpret the data accurately. When data is interpreted incorrectly, it can lead to huge losses.

- **Algorithm**: A process or set of rules to be followed for a specific task
- **Data-driven decision making**: we have the exact data you need to make a decision
- **Data-inspired decision making**: explores different data sources to find out what they have in common


### Quantitative and qualitative data

- **Quantitative data**: Specific and objective measures of numerical facts. This can often be the what, how many, and how often about a problem. In other words, things you can measure, like how many commuters take the train to work every week.
- **Qualitative data**: Subjective or explanatory measures of qualities and characteristics. I.e. things that can't be measured with numerical data, like your hair color. Qualitative data is great for helping us answer why questions and answers are often visualized in charts or graphs.



## Sharing our findings

- **Reports**: 
    - A static collection of data given periodically to stakeholders. 
    - Reports are great for giving snapshots of high level historical data for an organization
    - Quick to design an easy to use
    - Reflect data that is pre-cleaned and sorted
    - Need regular maintenance
    - Are less visually appealing
    
- **Dashboards**: 
    - Monitors live, incoming data
    - Dynamic, automatic and interactive
    - More stakeholder access
    - Low maintenance
    - Labor-intensive design
    - Can be confusing
    - Need more maintenance if underlying table breaks
    - Can contain potentially uncleaned data

A **pivot table** is a data summarization tool that is used in data processing. Pivot tables are used to summarize, sort, re-organize, group, count, total, or average data stored in a database. It allows its users to transform columns into rows and rows into columns. 


### More about dashboards

For a basic idea of what dashboards look like, refer to this article: [6 real-world examples of business intelligence dashboards](https://www.tableau.com/learn/articles/business-intelligence-dashboards-examples). Tableau is one tool that is used to create dashboards and is covered later in the program.

Often, businesses will tailor a dashboard for a specific purpose. The three most common categories are:

- Strategic: focuses on long term goals and strategies at the highest level of metrics
- Operational: short-term performance tracking and intermediate goals
- Analytical: consists of the datasets and the mathematics used in these sets


To create a dashboard:

1. Identify the stakeholders who need to see the data and how they will use it

To get started with this, you need to ask effective questions. Check out this [Requirements Gathering Worksheet](https://s3.amazonaws.com/looker-elearning-resources/Requirements+Gathering+Worksheet.pdf) to explore a wide range of good questions you can use to identify relevant stakeholders and their data needs. This is a great resource to help guide you through this process again and again. 

2. Design the dashboard (what should be displayed)

Use these tips to help make your dashboard design clear, easy to follow, and simple:

- Use a clear header to label the information
- Add short text descriptions to each visualization
- Show the most important information at the top

3. Create mock-ups if desired 

This is optional, but a lot of data analysts like to sketch out their dashboards before creating them. 

4. Select the visualizations you will use on the dashboard

5. Create filters as needed

Filters show certain data while hiding the rest of the data in a dashboard. This can be a big help to identify patterns while keeping the original data intact. It is common for data analysts to use and share the same dashboard, but manage their part of it with a filter. To dig deeper into filters and find an example of filters in action, you can visit Tableau’s page on [Filter Actions](https://help.tableau.com/current/pro/desktop/en-us/actions_filter.htm). 



## Data versus metrics

A **metric** is a single, quantifiable type of data that can be used for measurement. Think of it this way. Data starts as a collection of raw facts, until we organize them into individual metrics that represent a single type of data.

**ROI**, or Return on Investment is essentially a formula designed using metrics that let a business know how well an investment is doing. The ROI is made up of two metrics, the net profit over a period of time divided by the cost of investment.

A **metric goal** is a measurable goal set by a company and evaluated using metrics. 



## Mathematical thinking

- **Small data**:
    - Specific
    - Short time period
    - Day-to-day decisions
    - Simple to collect, store, manage, sort, and visually represent 
    - Usually organized and analyzed in spreadsheets

- **Big data**:
    - Large and less-specific
    - Long time-period
    - Usually kept in a database and queried
    - Takes a lot of effort to collect, store, manage, sort, and visually represent
    - Usually needs to be broken into smaller pieces in order to be organized and analyzed effectively for decision-making
    - Allows to look at large scale problems to make big decisions

Benefits of large data:

- When large amounts of data can be stored and analyzed, it can help companies identify more efficient ways of doing business and save a lot of time and money.
- Big data helps organizations spot the trends of customer buying patterns and satisfaction levels, which can help them create new products and solutions that will make customers happy.
- By analyzing big data, businesses get a much better understanding of current market conditions, which can help them stay ahead of the competition.
- As in our earlier social media example, big data helps companies keep track of their online presence—especially feedback, both good and bad, from customers. This gives them the information they need to improve and protect their brand.

Challenges to face with big data:

- A lot of organizations deal with data overload and way too much unimportant or irrelevant information. 
- Important data can be hidden deep down with all of the non-important data, which makes it harder to find and use. This can lead to slower and more inefficient decision-making time frames.
- The data you need isn’t always easily accessible. 
- Current technology tools and solutions still struggle to provide measurable and reportable data. This can lead to unfair algorithmic bias. 
- There are gaps in many big data business solutions.


### The three (or four) V words for big data

When thinking about the benefits and challenges of big data, it helps to think about the three Vs: volume, variety, and velocity. **Volume** describes the amount of data. **Variety** describes the different kinds of data. **Velocity** describes how fast the data can be processed. Some data analysts also consider a fourth V: **veracity**. Veracity refers to the quality and reliability of the data. These are all important considerations related to processing huge, complex data sets.



