# Working with databases

## Database features

- A **database** is a collection of data stored in a computer system.
- **Relational database**: A database that contains a series of related tables that can be connected via their relationships. They allow data analysts to organize and link data based on what the data has in common. For two tables to have a relationship, one or more of the same fields must exist inside both tables. Tables in a relational database are connected by the fields they have in common.
- **Normalization** is a process of organizing data in a relational database. For example, creating tables and establishing relationships between those tables. It is applied to eliminate data redundancy, increase data integrity, and reduce complexity in a database.
- **Primary key**: A identifier that references a column in which each value is unique. n other words, it's a column of a table that is used to uniquely identify each record within that table. If you do decide to include a primary key, it should be unique, meaning no two rows can have the same primary key. Also, it cannot be null or blank.
- **Foreign key**: A field within a table that is a primary key in another table. In other words, a foreign key is how one table can be connected to another. A table can have only one primary but multiple foreign keys. These keys are what create the relationships between tables in a relational database, which helps organize and connect data across multiple tables in the database. 
- Some tables don't require a primary key
- Both primary and foreign keys connect tables in relational databases
- A primary key may also be constructed using multiple columns of a table. This type of primary key is called a **composite key**


## Managing data with metadata

- **Metadata**: Data about data but not data itself. Metadata tells you where the data comes from, when and how it was created, and what it's all about. Metadata helps data analysts interpret the contents of the data within a database. Metadata also makes data more reliable by making sure it's accurate, precise, relevant, and timely.
- Metadata helps data analysts interpret the contents of the data within a database
- Examples of parts of metadata: Title and description, tags and categories, who created it and when it was created, who last modified it and when, who can access or update it?
- A **metadata repository** is a database specifically created to store metadata.These repositories describe where metadata came from, keep it in an accessible form so it can be used quickly and easily, and keep it in a common structure for everyone who may need to use it. They:
    - Describe the state and location of metadata
    - Describe the structures of the tables inside
    - Describe how the data flows through the repository
    - Keeps track of who accesses the metadata and when

Types of metadata:

- Descriptive: Metadata that describes a piece of data and can be used to identify it at a later point in time, i.e. ID numbers of students
- Structural: Metadata that indicates how a piece of data is organized and whether it is part of one, or more than one, data collection
- Administrative: Metadata that indicates the technical source and details of a digital asset, i.e. The date and time a photo was taken

Managing metadata:

- Metadata is stored in a single, central location and it gives the company standardized information about all of its data. This is done in two ways:
    - Metadata includes information about where each system is located and where the data sets are located within those systems
    -  The metadata describes how all of the data is connected between the various systems 
- **Data governance** is a process to ensure the formal management of a company’s data assets. This gives an organization better control of their data and helps a company manage issues related to data security and privacy, integrity, usability, and internal and external data flows.


## Accessing data sources

### Data import

**Google Sheets**

In Google Sheets, you can use the `IMPORTRANGE` function. It enables you to specify a range of cells in the other spreadsheet to duplicate in the spreadsheet you are working in. You must allow access to the spreadsheet containing the data the first time you import the data.


### Import HTML tables from the web

Importing HTML tables is a very basic method to extract or "scrape" data from public web pages. [Web scraping made easy](https://www.thedataschool.co.uk/anna-prosvetova/web-scraping-made-easy-import-html-tables-or-lists-using-google-sheets-and-excel) introduces how to do this with Google Sheets or Microsoft Excel.

**Google Sheets**

In Google Sheets, you can use the `IMPORTHTML` function. It enables you to import the data from an HTML table (or list) on a web page. 

**Excel**

- Step 1: Open a new or existing spreadsheet.
- Step 2: Click Data in the main menu and select the From Web option. 
- Step 3: Enter the URL and click OK.
- Step 4: In the Navigator, select which table to import.
- Step 5: Click Load to load the data from the table into your spreadsheet.



## Sorting and filtering

- **Sorting** involves arranging data into a meaningful order to make it easier to understand, analyze, and visualize
- **Filtering** means showing only the data that meets a specific criteria while hiding the rest




## Working with SQL

### Setting up BigQuery, including sandbox and billing options

BigQuery is a data warehouse on Google Cloud that data analysts can use to query, filter large datasets, aggregate results, and perform complex operations. 

Types of accounts: 

- A **Sandbox** account is available at no charge and anyone with a Google account can log in and use it. . There are a couple of limitations to this account type. For example, you get a maximum of 12 projects at a time. It also doesn't allow you to insert new records to a database or update the field values of existing records. Setup instructions are found [here](https://scribehow.com/shared/Use_the_BigQuery_Sandbox__2g5j853nR2-Ze5P_9w18tg)
- The **free trial** gives you access to more of what BigQuery has to offer with fewer overall limitations. The free trial offers 300 dollars in credit for use in Google Cloud during the first 90 days. After you spend the $300 credit or after 90 days, your free trial will expire and you will need to personally select to upgrade to a paid account to keep working in Google Cloud.

How to get to the BigQuery console:

- In your browser, go to console.cloud.google.com/bigquery taking you to the main dashboard for the Google Cloud Platform. To navigate to BigQuery from the dashboard, do the following:
    - Click the Navigation menu icon (Hamburger icon) in the banner.
    - Scroll down to the BIG DATA section.
    - Click BigQuery and select SQL workspace.


### Other databases

- [Getting started with MySQL](https://dev.mysql.com/doc/mysql-getting-started/en/): This is a guide to setting up and using MySQL.
- [Getting started with Microsoft SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/tutorial-getting-started-with-the-database-engine?view=sql-server-ver15): This is a tutorial to get started using SQL Server.
- [Getting started with PostgreSQL](https://www.postgresql.org/docs/10/tutorial-start.html): This is a tutorial to get started using PostgreSQL.
- [Getting started with SQLite](https://www.sqlite.org/quickstart.html): This is a quick start guide for using SQLite.


### Using BigQuery

**Play with some public data**

0. Go to console.cloud.google.com/bigquery
1. Navigate to the Explorer menu in BigQuery.
2. Type the word public in the search box and enter.
3  Click "Broaden search to all projects"
4. Find the bigquery-public-data and pin it.


### SQL basics

With SQL, **capitalization** usually doesn’t matter. You could write SELECT or select or SeLeCT. They all work! But if you use capitalization as part of a consistent style your queries will  look more professional.

To write SQL queries like a pro, it is always a good idea to use all caps for clause starters (e.g., SELECT, FROM, WHERE, etc.). Functions should also be in all caps (e.g., SUM()). Column names should be all lowercase (refer to the section on snake_case later in this guide). Table names should be in CamelCase (refer to the section on CamelCase later in this guide). This helps keep your queries consistent and easier to read while not impacting the data that will be pulled when you run them

For the most part, it also doesn’t matter if you use single **quotes** ' ' or double quotes " " when referring to strings. 

But there are two situations where it does matter what kind of quotes you use:

- When you want strings to be identifiable in any SQL dialect (i.e. WHERE country = 'US')
- When your string contains an apostrophe or quotation marks (i.e. "Shepherd's pie")

Within each SQL dialect there are rules for what is accepted and what isn’t. But a general rule across almost all SQL dialects is to use single quotes for strings. 

It is important to always make sure that the output of your query has easy-to-understand names. However, Never use spaces. The best practice is to use **snake_case**. This means that 'total tickets', which has a space between the two words, should be written as 'total_tickets' with an underscore instead of a space. 

You can also use **CamelCase** capitalization when naming your table. CamelCase capitalization means that you capitalize the start of each word, like a two-humped (Bactrian) camel. So the table TicketsByOccasion uses CamelCase capitalization.

As a general rule, you want to keep the length of each line in a query <= 100 characters. This makes your queries easy to read.

**Multi-line comments**
If you make comments that take up multiple lines, you can use -- for each line. Or, if you have more than two lines of comments, it might be cleaner and easier is to use /* to start the comment and */ to close the comment. 

Key terms:

- SELECT is the section of a query that indicates what data you want SQL to return to you
- FROM is the section of a query that indicates which table the desired data comes from. 
- WHERE is the section of a query that indicates any filters you’d like to apply to your dataset
- you’re sorting how you want your results to appear with ORDER BY.
- LIMIT tells SQL to only return the top five most popular names and their counts

```
SELECT name, count FROM `lithe-vault-366813.babynames.names_2014` 
WHERE gender = "M"
Order BY count DESC
LIMIT 5
```

Some more resources:

- [Search and replace in Sublime Text](https://sublime-text-unofficial-documentation.readthedocs.io/en/latest/search_and_replace/search_and_replace_overview.html)
- [Regex tutorial](https://www.regular-expressions.info/tutorialcnt.html) (if you don’t know what regular expressions are)
- [Regex cheat sheet](https://jdhao.github.io/2019/02/28/sublime_text_regex_cheat_sheet/)



