# Organizing data and managing your online presence

## Organzing data

- Makes it easier to find and use data, 
- Helps you avoid making mistakes during your analysis 
- Helps to protect data

**Naming conventions**: These are consistent guidelines that describe the content, date, or version of a file in its name. You want to use logical and descriptive names for your files to make them easier to find and use

Organizing your files into folders helps keep project-related files together in one place. This is called **foldering**.

Align your naming and storage practices and develop metadata practices with your team to avoid any confusion

### File naming

Recommendations for naming conventions:

When you use consistent guidelines that describe the content, date, or version of a file and its name, you're using **file naming conventions**. We can use metadata to to indicate consistent naming conventions for a project.

- Work out and agree on file naming conventions early on in a project to avoid renaming files again and again.
- Align your file naming with your team's or company's existing file-naming conventions.
- Ensure that your file names are meaningful; consider including information like project name and anything else that will help you quickly identify (and use) the file for the right purpose.
- Include the date and version number in file names; common formats are YYYYMMDD for dates and v## for versions (or revisions).
- Create a text file as a sample file with content that describes (breaks down) the file naming convention and a file name that applies it.
- Avoid spaces and special characters in file names. Instead, use dashes, underscores, or capital letters. Spaces and special characters can cause errors in some applications.
- Lead revision numbers with 0: v02
- Create a text file that lays out all your naming conventions on a project. This is really helpful if someone new joins your team,


## Securing data

**Security features** can be designed to keep unauthorized users from viewing certain files, or just lock your worksheets so that you don't accidentally break your formulas. This is called data security.

**Data security** means protecting data from unauthorized access or corruption by adopting safety measures. 

**Encryption** uses a unique algorithm to alter data and make it unusable by users and applications that don’t know the algorithm. This algorithm is saved as a “key” which can be used to reverse the encryption; so if you have the key, you can still use the data in its original form.  

**Tokenization** replaces the data elements you want to protect with randomly generated data referred to as a “token.” The original data is stored in a separate location and mapped to the tokens. To access the complete original data, the user or application needs to have permission to use the tokenized data and the token mapping. This means that even if the tokenized data is hacked, the original data is still safe and secure in a separate location. 


## Building a network

Podcasts to follow, like Partially Derivative and the O'Reilly Data Show.

For instance, websites like Score.org and MicroMentor.org and an app called Mentorship allow you to look for specific credentials that match your needs.





